// import type { Metadata } from "next";

import "./globals.css";
import NavBar from "./custom/navBar";
import Container from "./custom/container";
import { ThemeProvider } from "./custom/theme-provider";

import { nunitoSans } from "@/lib/font";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const experimental_ppr = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.className} antialiased transition-all duration-500`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
        >
          <header className="w-screen shadow-lg dark:bg-darkBlue dark:text-white text-veryDarkBlue duration-200 transition-all">
            <Container>
              <NavBar />
            </Container>
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
